### ISSUE TITLE
can't launch with blank ssh passphrase

### ISSUE THREAD

**Issue by skomputer** [gansbrest/hodor#12]
My SSH passphrase is blank, so I just hit enter when I'm prompted for it. But the hodor script quits with the message, "Your ssh key was not loaded correctly, try one more time."

It seems that in this case the `$?.exitstatus` is not `0` even though the passphrase is correct. Hodor proceeds and launches my container without errors if I comment out this line:

```
abort("Your ssh key was not loaded correctly, try one more time.")
```

**Comment by gansbrest** [comment]
if there is no password on the key, hodor wont ask for it ( that's default functionality of ssh agent ). When you commented out that line, it let you through but your key probably wasn't loaded correctly. 

Maybe you have multiple keys in your .ssh folder? At the moment hodor takes only id_rsa, which might be protected by password.
