### ISSUE TITLE
Docs aren't clear on what the "containers" block in config is for

### ISSUE THREAD

**Issue by duro** [gansbrest/hodor#7]
@gansbrest I'm a little uncertain how the "containers" block in the config factors in to everything. Is it supposed to work like the Fig project (www.fig.sh) where it will actually spin up my cluster for me in Boot2Docker?

I think this project has a lot of use for people working on Node and Front-end based projects that rely on file watchers to do their work. This is a problem I have been working on for quite some time with no luck. I have been trying to integrate Unison into the solution, but it seems you have found a much cleaner way to do that. I'd like to learn more about how we can start leveraging Hodor, and help contribute to it's development.

**Comment by gansbrest** [comment]
Not sure if it's still active. Closing for now.

**Comment by jbenoit2011** [comment]
What if I use `docker-compose`? Does it mean I have to duplicate it in the hodorfile?

**Comment by gansbrest** [comment]
Hodor is alternative to docker compose with some special sauce on top
(especially important is volume sharing). We use just hodor, but if you
want to have both, then yes you need to create .hodorfile as well (some
parts are different from compose one)
